export const SET_ADA_LAUNCH_AMOUNT = 'SET_ADA_LAUNCH_AMOUNT'
export const GET_AVAILABLE_QUANTITIES_SUCCESS = 'GET_AVAILABLE_QUANTITIES_SUCCESS'
export const GET_AVAILABLE_QUANTITIES_FAILED = 'GET_AVAILABLE_QUANTITIES_FAILED'
export const GET_POLICY_IDS_SUCCESS = 'GET_POLICY_IDS_SUCCESS'