export const FETCH_DISCOVERIES_STARTED = 'FETCH_DISCOVERIES_STARTED'
export const FETCH_DISCOVERIES_SUCCESS = 'FETCH_DISCOVERIES_SUCCESS'
export const FETCH_DISCOVERIES_ERROR = 'FETCH_DISCOVERIES_ERROR'